### ISSUE TITLE
No error, every port reads zero

### ISSUE THREAD

**Issue by Ghostbird** [adafruit/Adafruit_CircuitPython_MAX31855#19]
I can't get any reading from my two connected max31855, I'm not sure what I'm doing wrong. The library never gives a read error, I read the raw data too, using `adafruit_bus_device.spi_device.SPIDevice` which is simply all zeroes. This probably means that nothing is read into the data array, but I would expect an error if there is nothing on the bus at all.

This is my test program, it tries to read SPI data using every board defined digital GPIO pin as CS in sequence:

```python3
#!virtualenv/bin/python3
# -*- coding: utf-8 -*-
from adafruit_max31855 import MAX31855
from adafruit_bus_device.spi_device import SPIDevice
from busio import SPI
from digitalio import DigitalInOut
import board

if __name__ == '__main__':
  spi = SPI(clock=board.SCK, MOSI=board.MOSI, MISO=board.MISO)
  pins = (DigitalInOut(board.__dict__[pin]) for pin in board.__dict__.keys() if pin[0] == 'D')
  for pin in pins:
    data = bytearray(4)
    with SPIDevice(spi, pin) as spi:
      spi.readinto(data)
    print('RAW: {}'.format(data))
    print(MAX31855(spi, pin).temperature)
```

**Comment by FoamyGuy** [comment]
Instead of Github issues, please ask for support for things like this on the forums: https://forums.adafruit.com/ or one of the #help-with channels in the Discord: https://adafru.it/discord. 

I don't think you need to loop over every pin like this. Why not just use the ones hat the sensors are actually wired to? Try the wiring and example code from here: https://learn.adafruit.com/thermocouple/python-circuitpython#python-computer-wiring-4-3
Once this is working with a single sensor then try adding another with a different CS pin.

**Comment by Ghostbird** [comment]
I'll take this to Discord.
This demonstration program is meant to show that even when I loop over every pin, and read the raw data, nothing is received. I'd at least expect to see a difference in behaviour between the pins with no chip attached and those _with_ chips attached.
